"""Unit test for the sensitive-pasteboard-type skip logic, without touching the real clipboard."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from clipmind.monitor import _is_sensitive


class FakePasteboard:
    def __init__(self, types):
        self._types = types

    def types(self):
        return self._types


cases = [
    (["public.utf8-plain-text"], False),
    (["public.utf8-plain-text", "org.nspasteboard.ConcealedType"], True),
    (["org.nspasteboard.TransientType"], True),
    (["org.nspasteboard.AutoGeneratedType", "public.utf8-plain-text"], True),
    ([], False),
]

results = []
for types, expected in cases:
    got = _is_sensitive(FakePasteboard(types))
    ok = got == expected
    results.append(ok)
    print(f"{'PASS' if ok else 'FAIL'}  types={types} got={got} expected={expected}")

total, passed = len(results), sum(results)
print(f"\n{passed}/{total} passed")
if passed != total:
    sys.exit(1)
