"""Clipboard monitor daemon: polls NSPasteboard for changes and stores classified clips."""
import time
import sys

from AppKit import NSPasteboard, NSWorkspace, NSStringPboardType, NSPasteboardTypeString

from . import store
from .classifier import classify

POLL_INTERVAL = 0.5
MAX_CONTENT_CHARS = 50_000

# De-facto clipboard-manager convention (used by 1Password, Bitwarden, Maccy, Paste, ...):
# an app marks a pasteboard entry with one of these types to say "don't persist this".
# Respecting it keeps ClipMind from permanently logging passwords / OTP codes / secrets.
SENSITIVE_TYPES = (
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
)


def _is_sensitive(pb) -> bool:
    try:
        types = set(pb.types())
    except Exception:
        return False
    return any(t in types for t in SENSITIVE_TYPES)


def _read_pasteboard_string(pb) -> str | None:
    try:
        s = pb.stringForType_(NSPasteboardTypeString)
    except Exception:
        s = None
    if s is None:
        try:
            s = pb.stringForType_(NSStringPboardType)
        except Exception:
            s = None
    return str(s) if s is not None else None


def _frontmost_app_name() -> str | None:
    try:
        app = NSWorkspace.sharedWorkspace().frontmostApplication()
        if app is None:
            return None
        return str(app.localizedName())
    except Exception:
        return None


def poll_tick(pb, conn, last_change_count: int, verbose: bool = True) -> int:
    """Check the pasteboard once; store a new clip if it changed. Returns the change count to compare next time.

    Shared by the CLI daemon (run, below) and the menu-bar app (menubar.py) so
    both use exactly the same capture/classify/skip-sensitive logic.
    """
    cc = pb.changeCount()
    if cc == last_change_count:
        return cc
    if _is_sensitive(pb):
        if verbose:
            print("[다시봄] skipped (marked sensitive by source app)", flush=True)
        return cc
    text = _read_pasteboard_string(pb)
    if text:
        text = text[:MAX_CONTENT_CHARS]
        category, subtype = classify(text)
        app_name = _frontmost_app_name()
        new_id = store.add_clip(conn, text, category, subtype, app_name)
        if verbose and new_id:
            preview = text.replace("\n", " ")[:60]
            print(f"[다시봄] #{new_id} [{category}{'/' + subtype if subtype else ''}] "
                  f"({app_name}) {preview!r}", flush=True)
    return cc


def run(poll_interval: float = POLL_INTERVAL, max_iterations: int | None = None, verbose: bool = True):
    conn = store.connect()
    pb = NSPasteboard.generalPasteboard()
    last_change_count = pb.changeCount()

    if verbose:
        print(f"[다시봄] monitoring started (poll={poll_interval}s, db={store.DB_PATH})", flush=True)

    iterations = 0
    try:
        while True:
            last_change_count = poll_tick(pb, conn, last_change_count, verbose=verbose)
            time.sleep(poll_interval)
            iterations += 1
            if max_iterations is not None and iterations >= max_iterations:
                break
    except KeyboardInterrupt:
        if verbose:
            print("\n[다시봄] stopped", flush=True)
    finally:
        conn.close()


if __name__ == "__main__":
    run()
